version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: PetFamilyDB
      POSTGRES_USER: kas
      POSTGRES_PASSWORD: 4788959
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

